releases:
# - name: secrets
#
#   namespace: artemis
#   createNamespace: true
#   chart: ./secrets
#   kubeContext: chad-lb9937
#   labels:
#        app: userpasswords
#   values:
#    - users:
#          csl04r: csl04r
#          james: james
 - name: artemis
   namespace: artemis
   createNamespace: true
   chart: ../charts/artemis
   kubeContext: chad-lb9937
   values:
     - appRoleSecrets:
          roleId: {{ exec "op" (list "read" "op://Sherwin/qvgybl6xcm77yc5yl4f2crkxyu/role-id") }}
          secretId: {{ exec "op" (list "read" "op://Sherwin/qvgybl6xcm77yc5yl4f2crkxyu/secret-id") }}
     - global:
         shwCostCenter: lb9937
     - service:
         loadBalancer:
           annotations:
             metallb.universe.tf/allow-shared-ip: "10.20.132.79"
             metallb.universe.tf/ip-allocated-from-pool: "default-pool"
     - debugStatefulSet: false
     - persistence:
         enabled: true
         storageClass: longhorn
         accessModes: [ "ReadWriteOnce" ]
         storageSize: 8Gi
     - podSecurityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
     - users:
         csl04r:
           user: csl04r
           secretName: userpasswords
           secretKey: csl04r
         james:
              user: james
              secretName: userpasswords
              secretKey: james
     - roleBindings:
         - role: amq-admin
           users:
             - csl04r
         - role: amq-user
           users:
             - james
             - csl04r
     - addresses:
       - name: DLQ
       - name: ExpiryQueue
       - name: SherColor.TintOrder
     - security:
         kubernetes:
           ## security.kubernetes.enabled if `true` use kubernetes service account token authentication and authorization
           enabled: true
           clients:
             ## security.kubernetes.clients[].name name of a known applications that will connect from the K8s cluster, used to create an AMQ role and destination prefix
             - name: shercolor
               ## security.kubernetes.clients[].fullyQualifiedServiceAccountName the fully qualified service account name to acquire this AMQ role
               fullyQualifiedServiceAccountName: system:serviceaccount:shw-na-pos:shercolor
             - name: pol
               fullyQualifiedServiceAccountName: system:serviceaccount:shw-na-pos:pol
             - name: CHAD
               fullyQualifiedServiceAccountName: system:serviceaccount:default:chad-amq-client
           ## security.kubernetes.roleAliases maps ActiveMQ roles to a list of k8s principals
           roleAliases:
             amq: # the activemq role to assign
               ## security.kubernetes.roleAliases.amq[] list of k8s prinicpals to get the `amq` role
               - system:serviceaccount:shw-na-pos:pol # list of k8s principals to receive the role
               - system:serviceaccount:shw-na-pos:shercolor
         oauth2:
           ## security.oauth2.enabled if `true` use OAuth2 JWT token authentication and authorization
           enabled: true
           ## security.oauth2.jaasModule LoginModule implementation class
           jaasModule: shw.activemq.extension.security.OAuth2LoginModule
           ## security.oauth2.tenantId In Microsoft Entra, the tenant ID in use
           tenantId: 44b79a67-d972-49ba-9167-8eb05f754a1a
           ## security.oauth2.audience audience in JWT which identifies this group of ActiveMQ services
           audience: 8bddbe55-946d-4033-8832-a1e752e97709
           ## security.oauth2.issuerUrl the URL of the OAuth2 issuer
           issuerUrl: https://login.microsoftonline.com/44b79a67-d972-49ba-9167-8eb05f754a1a/v2.0
           ## security.oauth2.rolesClaimName name of claim in the JWT containing roles to add to the authenticated subject
           rolesClaimName: roles
           # security.oauth2.roleAliases maps JWT roles to ActiveMQ roles. The ActiveMQ roles are the keys which take a list of JWT roles to which to grant the ActiveMQ role.
           roleAliases:
             amq: # the ActiveMQ role to assign to the JWT role
               ## security.oauth2.roleAliases.amq[] list of elements in the roles claim to get the `amq` ActiveMQ role
               - CCN.BANKCARD.INFO # the JWT role to assign to the ActiveMQ role
               - CCN.STORE.INFO
