repositories:
  - name: rt
    url: https://artifactory.sherwin.com/artifactory/helm-local
releases:
# - name: secrets
#
#   namespace: artemis
#   createNamespace: true
#   chart: ./secrets
#   kubeContext: chad-lb9937
#   labels:
#        app: userpasswords
#   values:
#    - users:
#          csl04r: csl04r
#          james: james
 - name: artemis
   namespace: artemis
   createNamespace: true
   chart: ../charts/artemis
#   chart: rt/activemq-artemis
#   version: 1.9.1
   kubeContext: chad-lb9937
   values:
     - ingress:
         enabled: true
         tls:
           secretName: artemis-tls
     - fullnameOverride: artemis
     - appRoleSecrets:
          roleId: {{ exec "op" (list "read" "op://Sherwin/qvgybl6xcm77yc5yl4f2crkxyu/role-id") }}
          secretId: {{ exec "op" (list "read" "op://Sherwin/qvgybl6xcm77yc5yl4f2crkxyu/secret-id") }}
     - global:
         shwCostCenter: lb9937
     - pycertmanager:
         enabled: true
#         image:
#           repository: docker.artifactory.sherwin.com/sherwin-williams-co/pycertmanager
#           tag: 0.0.4
     - service:
         loadBalancer:
           annotations:
             metallb.universe.tf/allow-shared-ip: "10.20.132.79"
             metallb.universe.tf/ip-allocated-from-pool: "default-pool"
     - debugStatefulSet: false
     - persistence:
         enabled: true
         storageClass: longhorn
         accessModes: [ "ReadWriteOnce" ]
         storageSize: 8Gi
     - podSecurityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
     - users:
         csl04r:
           user: csl04r
           secretName: userpasswords
           secretKey: csl04r
         james:
              user: james
              secretName: userpasswords
              secretKey: james
     - roleBindings:
         - role: amq-admin
           users:
             - csl04r
         - role: amq-user
           users:
             - james
             - csl04r
     - addresses:
       - name: DLQ
       - name: ExpiryQueue
       - name: SherColor.TintOrder
     - security:
         kubernetes:
           enabled: true
           roleAliases:
             amq:
               - system:serviceaccount:shw-na-pos:kafka-router # list of k8s principals to receive the role
               - system:serviceaccount:shw-na-pos:shercolor
         oauth2:
           enabled: true
           jaasModule: shw.activemq.extension.security.OAuth2LoginModule
#           tenantId: 44b79a67-d972-49ba-9167-8eb05f754a1a
#           audience: 8bddbe55-946d-4033-8832-a1e752e97709
#           issuerUrl: https://login.microsoftonline.com/44b79a67-d972-49ba-9167-8eb05f754a1a/v2.0

           tenantId: 8df001ce-a5dc-4dba-9efe-1effae06e270
           v1audience: api://7eb84ccd-d576-4998-9f16-193e2f990353
           audience: 7eb84ccd-d576-4998-9f16-193e2f990353
           v1issuerUrl: https://sts.windows.net/76928537-7d3e-4020-b43b-ad6dc9d7d97e/
           issuerUrl: https://login.microsoftonline.com/76928537-7d3e-4020-b43b-ad6dc9d7d97e/v2.0
           rolesClaimName: roles
           # security.oauth2.roleAliases maps JWT roles to ActiveMQ roles. The ActiveMQ roles are the keys which take a list of JWT roles to which to grant the ActiveMQ role.
           roleAliases:
             CHAD:
               - Chad.Manage
#             amq: # the ActiveMQ role to assign to the JWT role
#               ## security.oauth2.roleAliases.amq[] list of elements in the roles claim to get the `amq` ActiveMQ role
#               - CCN.BANKCARD.INFO # the JWT role to assign to the ActiveMQ role
#               - CCN.STORE.INFO
